### ISSUE TITLE
Style : Todo List UI 구현

### ISSUE THREAD

**Issue by yoonhe** [yoonhe/wanted_paywork_todoList#5]
- [x] Task Board UI
- [x] Todo List UI Todo name 
- [x] 완료 상태 표시
- [x] 미완료, 완료 영역 분리
